export { default as Register } from './Register';
export { default as Login } from './Login'
export { default as OTP } from './OTP'
export { default as ForgotPassword } from './ForgotPassword'
export { default as Dashboard } from './Dashboard'
export { default as TaskCanvasPage } from './TaskCanvasPage';
export { default as TimesheetPage } from './TimesheetPage';
export { default as TimesheetsView } from './TimesheetsView';
export { default as UserManagement } from './UserManagement';